config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get  'home'                 => 'home#home'
  get  'pesquisa'             => 'reservas#pesquisa'
  post 'pesquisa'             => 'reservas#pesquisa'
  get  'login'                => 'sessions#new'
  post 'login'                => 'sessions#create'
  post 'criar_funcionario'    => 'funcionarios#create'
  get 'adm'                   => 'funcionarios#adm'
  get 'index_interditar'      => 'salas#index_interditar'
  
  patch 'pre_edicao'          => 'reservas#pre_edicao'
  get  'main'                 => 'formularios#main'
  post 'filtro_salas'         => 'formularios#filtro_salas'
  post 'dados_reserva'        => 'formularios#dados_reserva'
  post 'criar_reserva'        => 'formularios#criar_reserva'
  post 'confirmar_reserva'    => 'formularios#confirmar_reserva'
  get  'impressao'            => 'formularios#impressao'
  
  post 'selecao_velorio'           => 'reservas#selecao_velorio'
  post 'velorio_interditar' => 'salas#selecao_velorio_interditar'
  patch 'interditar_sala' => 'salas#interditar_sala'

  delete 'logout'             => 'sessions#destroy'
  
  resources 'salas'
  resources 'funcionarios'
  resources 'reservas'
  resources 'justificativas'
  
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  include FormulariosHelper

  def main
    @reserva = Reserva.new
    @cem_aux = []
    gon.cemiterios = {}
    Cemiterio.all.each do |c|
      if !c.outro
        @cem_aux << [c.nome, c.id]
        gon.cemiterios[c.id] = c
      end
    end
    @cemiterios = @cem_aux << ["Outro", 0]
    @cemiterios = @cemiterios.sort
  end

def filtro_salas
  if params[:mesmo_local] == "Sim"
    @cemiterio = Cemiterio.find(params[:cemiterio_id]).id
    @nome_cemiterio = Cemiterio.find(@cemiterio).nome
    @velorio = Velorio.find_by(nome: @nome_cemiterio)
    if @velorio.nome == 'Vila Formosa II'
      @matriz = geraMatriz(@velorio, 15)
      @colspan_central = 96
      @colspan_borda_esq = @colspan_central - Time.now.hour.to_i * 4 - 4
      @colspan_borda_dir = Time.now.hour.to_i * 4 + 8
    else
      @matriz = geraMatriz(@velorio, 60)
      @colspan_central = 24
      @colspan_borda_esq = @colspan_central - Time.now.hour.to_i - 1
      @colspan_borda_dir = Time.now.hour.to_i + 2
    end
  else
    if params[:cemiterio_id] == "0"
      @cemiterio = Cemiterio.create(nome: params[:outro], outro: true).id
    else
      @cemiterio = Cemiterio.find(params[:cemiterio_id]).id
    end
    @velorio = Velorio.find(params[:velorio_id])
    if @velorio.nome == 'Vila Formosa II'
      @matriz = geraMatriz(@velorio, 15)
      @colspan_central = 96
      @colspan_borda_esq = @colspan_central - Time.now.hour.to_i * 4 - 4
      @colspan_borda_dir = Time.now.hour.to_i * 4 + 8
    else
      @matriz = geraMatriz(@velorio, 60)
      @colspan_central = 24
      @colspan_borda_esq = @colspan_central - Time.now.hour.to_i - 1
      @colspan_borda_dir = Time.now.hour.to_i + 2
    end
  end
  respond_to do |format|
    format.js
  end
end

  def dados_reserva
    @sepultamento = params[:sepultamento]
    @sala = Sala.find(params[:sala_id])
    @velorio = Velorio.find(params[:velorio_id])
    @cemiterio = Cemiterio.find(params[:cemiterio_id])
    @atendente = current_funcionario
    @reserva = Reserva.new

    respond_to do |format|
      format.js
    end
  end

  def criar_reserva
    @reserva = Reserva.new(
               cemiterio_id: params[:cemiterio], velorio_id: params[:velorio], sala_id: params[:sala],
               sepultamento: params[:sepultamento], d_obito: params[:d_obito], falecido: params[:n_falecido],
               municipe: params[:n_municipe], atendente_id: current_funcionario.id, ncf: params[:ncf])
    respond_to do |format|
        format.js
    end
  end

  def confirmar_reserva
    @reserva = Reserva.create(
               cemiterio_id: params[:reserva][:cemiterio_id], velorio_id: params[:reserva][:velorio_id], sala_id: params[:reserva][:sala_id],
               sepultamento: params[:reserva][:sepultamento], d_obito: params[:reserva][:d_obito], falecido: params[:reserva][:falecido],
               municipe: params[:reserva][:municipe], atendente_id: current_funcionario.id, contratacao: Time.now.in_time_zone, ncf: params[:reserva][:ncf])
    redirect_to root_url
  end

  def impressao
    redirect_to root_url if !params[:reserva]
    @reserva = Reserva.new(
               cemiterio_id: params[:reserva][:cemiterio_id], velorio_id: params[:reserva][:velorio_id], sala_id: params[:reserva][:sala_id],
               sepultamento: params[:reserva][:sepultamento], d_obito: params[:reserva][:d_obito], falecido: params[:reserva][:falecido],
               municipe: params[:reserva][:municipe], atendente_id: current_funcionario.id)
  end

end

app/helpers/formularios_helper.rb
module FormulariosHelper

	def geraMatriz(velorio, parametro)
		divisor = 60/parametro

		matriz = Array.new(velorio.salas.count+1) { Array.new(48*divisor+1) }

		#Construindo a matriz
		matriz[0][0] = ""

		horario_atual = round_to_next_x_minutes(Time.now.in_time_zone, parametro)
		for y in 1..(48*divisor+1)
			matriz[0][y] = horario_atual
			horario_atual = horario_atual + (parametro * 60)
		end

		for x in 1..velorio.salas.count
			matriz[x][0] = x
		end
		#Fim da construção
		trocou_dia = false

		for x in 1..velorio.salas.count
			ultimo_sepultamento_sala = ultimoSepultamento(velorio.salas[x-1])
				for y in 1..(48*divisor+1)
					trocou_dia = true if matriz[0][y] == 0
					if trocou_dia
						if !ultimo_sepultamento_sala.nil? && matriz[0][y] <= ultimo_sepultamento_sala
							matriz[x][y] = 'p' #Periodo preenchido
						elsif velorio.salas[x-1].desabilitada
							matriz[x][y] = 'o' #sala ocupada
						else
							matriz[x][y] = matriz[0][y] #Periodo vago
						end
					else
						if !ultimo_sepultamento_sala.nil? && matriz[0][y] <= ultimo_sepultamento_sala
							matriz[x][y] = 'p' #Periodo preenchido
						elsif velorio.salas[x-1].desabilitada
							matriz[x][y] = 'o' #sala ocupada
						else
							matriz[x][y] = matriz[0][y] #Periodo vago
						end
					end
				end
				trocou_dia = false
		end
		return matriz
	end

	def ultimoSepultamento(sala)
		sala.reservas.where(excluida: nil).order(sepultamento: :desc).first.try(:sepultamento)
	end

	def round_to_next_x_minutes(horario, x)
		intervalo = 60/x
		i = 1
		minutos = horario.strftime("%M").to_i
		intervalo.times do
			if minutos < x * i
				return horario.beginning_of_hour + x * 60 * i
			end
			i = i + 1
		end
	end

end

app/views/formularios/_concluir_reserva.html.erb
<div class="row setup-content step hiddenStepInfo" id="step-4">
	<div id="conclusao"></div>
</div>

app/views/formularios/_dados_reserva.html.erb
<div class="row setup-content step hiddenStepInfo" id="step-3">
	<div id="formulario"></div>		
</div>

app/views/formularios/_filtro_salas.html.erb
<div class="row setup-content step hiddenStepInfo" id="step-2">
	<div id="matriz">
		<%= image_tag("loading.gif", :id => "loading") %>
		<h3>Carregando</h3>
	</div>
</div>

app/views/formularios/_fim.html.erb
<div class="col-xs-12">
  <div>
    <input type="button" id="voltar_sala" class="dangerBut" value="Voltar" onclick="javascript: resetActive(event, 75, 'step-3');">
    <%= link_to "Imprimir", impressao_path(:reserva => @reserva.attributes), :target => '_blank', class: 'cibelbutton' %>
    <%= link_to "Confirmar reserva", confirmar_reserva_path(:reserva => @reserva.attributes), :method => :post , class: 'myButton' %>
  </div>
  <div class="col-md-offset-4 painel tam6 text-center">
    <div class="titulo centralizar-texto">
      <h2>Confirme os dados</h2>
    </div>  
    <div class="conteudo-painel" style="text-align: left">
      
      <table class="table table-striped table-bordered" border=0 width=100%>
        <tr>
          <td class="left">Nome do Contratante:</td>
          <td><%= @reserva.municipe %></td>
        </tr>
         <tr>
          <td class="left">Nome do Falecido:</td>
          <td><%= @reserva.falecido %></td>
        </tr>
         <tr>
          <td class="left">Número da Declaração de Óbito:</td>
          <td><%= @reserva.d_obito %></td>
        </tr>
         <tr>
          <td class="left">Número da Nota de Contratação:</td>
          <td><%= @reserva.ncf %></td>
        </tr>
         <tr>
          <td class="left">Cemitério:</td>
          <td><%= Cemiterio.find(@reserva.cemiterio_id).nome %></td>
        </tr>
         <tr>
          <td class="left">Velório:</td>
          <td><%= Velorio.find(@reserva.velorio_id).nome %></td>
        </tr>
         <tr>
          <td class="left">Sala:</td>
          <td><%= Velorio.find(@reserva.velorio_id).salas.index(Sala.find(@reserva.sala_id)).to_i + 1 %></td>
        </tr>
         <tr>
          <td class="left">Horario de Sepultamento:</td>
          <td><%= @reserva.sepultamento.strftime("%d/%m/%Y %H:%M") %></td>
        </tr>
         <tr>
          <td class="left">Data de Contratação:</td>
          <td><%= Time.now.in_time_zone.strftime("%d/%m/%Y %H:%M") %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/formularios/_formulario.html.erb
<div class="col-xs-12">
	<%= form_tag criar_reserva_path, :method => 'post', remote: true do |f| %>
		<div>
			<input type="button" id="voltar_sala" class="dangerBut" value="Voltar" onclick="javascript: resetActive(event, 25, 'step-2');">
			<input type="button" id="botao_criar_reserva" class="myButton" value="Próximo Passo">
			<%= submit_tag "Próximo passo", class: 'cibelbutton', id: "cib_submit", style: "display: none;", onclick:"javascript: resetActive(event, 75, 'step-4');" %>
		</div>
		<div class="painel col-md-4 col-md-offset-4 text-center">
			<div class="titulo centralizar-texto">
				<h2>Preencha os dados</h2>
			</div>

		<div class="row conteudo-painel">
			<div class="col-md-7 cib_left">
				<%= label_tag "Declaração de Óbito:", nil, class: "cib_label" %>
				<%= label_tag "Nº da Nota de Contratação:", nil, class: "cib_label" %>
				<%= label_tag "Nome do Falecido:", nil, class: "cib_label" %>
				<%= label_tag "Nome do Munícipe Responsável:", nil, class: "cib_label" %>
			</div>
			<div class="col-md-5">
				<%= text_field_tag :d_obito, nil, maxlength: 6, class: "cib_input", id: "form_d_obito" %>
				<%= text_field_tag :ncf, nil, maxlength: 7, class: "cib_input", id: "form_ncf" %>
				<%= text_field_tag :n_falecido, nil, class: "cib_input", id: "form_n_falecido" %>
				<%= text_field_tag :n_municipe, nil, class: "cib_input", id: "form_n_municipe" %>
			</div>
			<%= hidden_field_tag :cemiterio, @cemiterio.id %>
			<%= hidden_field_tag :velorio, @velorio.id %>
			<%= hidden_field_tag :sala, @sala.id %>
			<%= hidden_field_tag :sepultamento, @sepultamento %>
		</div>
	
	<% end %>

		<button id="botao_modal" style="display: none;" type="button" data-toggle="modal" data-target="#modal-form"></button>

		<div class="modal fade" id="modal-form" role="dialog">
		  <div class="modal-dialog">
		    <div class="cimodal tam6 col-md-offset-1">
		      <div class="titulo">
		        <button type="button" class="close" data-dismiss="modal">&times;</button>
		        <h4 class="modal-title">Operação errada!</h4>
		      </div>
		      <div class="conteudo-modal">
		        <p>Por favor, preencha todos os campos.</p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="dangerBut" data-dismiss="modal">Fechar</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
</div>

app/views/formularios/_sala.html.erb
<%= form_tag dados_reserva_path, :method => 'post', remote: true do |f| %>
  <div>
    <%= link_to "Voltar", main_path, class: "dangerBut" %>
    <%= submit_tag "Próximo passo", id: "prox-passo", class: "myButton" %>
  </div>
  <div class="painel col-md-12 text-center">
    <div class="titulo centralizar-texto">
      <h2>Selecione a sala e horário de sepultamento</h2>
    </div>

    <h2><%= @velorio.nome %></h2>

    <%= render 'layouts/matriz', object: @matriz %>

  	<div class="conteudo-painel">
  	  <%= hidden_field_tag(:sepultamento, value = nil) %>
  	  <%= hidden_field_tag(:sala_id, value = nil) %>
  	  <%= hidden_field_tag(:cemiterio_id, value = @cemiterio) %>
  	  <%= hidden_field_tag(:velorio_id, value = @velorio.id) %>
  	</div>
<% end %>

  <!-- Trigger the modal with a button -->
    <button id="modal-erro" style="display: none;" type="button" data-toggle="modal" data-target="#myModal">Open Modal</button>
   <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="cimodal tam6 col-md-offset-1">
          <div class="titulo">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Operação errada!</h4>
          </div>
          <div class="conteudo-modal">
            <p>Por favor, selecione um horário para o velorio e tente novamente!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="dangerBut" data-dismiss="modal">Fechar</button>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/formularios/_selecao_velorio.html.erb
<div class="setup-content step activeStepInfo" id="step-1">
	<%= form_tag filtro_salas_path, :method => 'post', remote: true do |f| %>
		<div>
			<input type="button" id="sel_vel_sub" class="myButton" value="Próximo Passo">
			<%= submit_tag "Próximo passo", class: 'cibelbutton', id: "prox_pass_but", style: "display: none", onclick:"javascript: resetActive(event, 25, 'step-2');" %>
			</input>					
		</div>
		
	<div class="painel tam6 col-md-offset-4">
		<div class="titulo centralizar-texto">
			<h2>Selecione o local de sepultamento</h2>
		</div>
		<div class="conteudo-painel">			
				<%= label_tag :cemiterio_id, "Local de Sepultamento/Cremação" %>
				<%= select_tag :cemiterio_id, options_for_select(@cemiterios), class: 'form-control' %><br>
				<%= label_tag :outro, "Digite o nome do cemitério", id: "label_outro" %>
				<%= text_field_tag "outro", nil, class: 'form-control' %>
				<br>
				<%= label_tag :mesmo_local, "Velório será no mesmo local de sepultamento?" %>
				<%= select_tag :mesmo_local, options_for_select(['Sim','Não']), class: 'form-control' %><br>
				<div id="velorio">
					<%= label_tag :velorio_id, "Selecione o local de velório" %>
					<%= select_tag :velorio_id, options_for_select(Velorio.all.collect{ |v| [v.nome, v.id] }), class: 'form-control' %>
				</div>				
			<% end %>
		</div>
	</div>
</div>

<button id="botao_modal_sel" style="display: none;" type="button" data-toggle="modal" data-target="#modal-form"></button>

<div class="modal fade" id="modal-form" role="dialog">
  <div class="modal-dialog">
    <div class="cimodal tam6 col-md-offset-1">
      <div class="titulo">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Operação errada!</h4>
      </div>
      <div class="conteudo-modal">
        <p>Por favor, preencha todos os campos.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="dangerBut" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/formularios/criar_reserva.js.erb
$('#conclusao').html("<%= j render 'formularios/fim' %>");

app/views/formularios/dados_reserva.js.erb
$('#formulario').html("<%= j render 'formularios/formulario', object: @reserva %>");

app/views/formularios/filtro_salas.js.erb
$('#matriz').html("<%= j render 'formularios/sala', object: @matriz  %>");

var clicou = false;

$(function() {
    $('td.td_livre').click( function() {
        clicou = true;
    	$('.agenda_livre').css('background-color', '#fff'); //Altera tudo pro padrão normal
        document.getElementById('sepultamento').value = $(this).find('.agenda_livre').attr("data-horario");
        document.getElementById('sala_id').value = $(this).find('.agenda_livre').attr("data-sala");

        //Guarda a sala
        var sala = $(this).find('.agenda_livre').attr("data-sala");

        //Pinta o que foi clicado
        $(this).find('.agenda_livre').css('background-color', 'yellow');

        //Pinta todos os outros
        $(this).prevAll('td.td_livre').each(function(){
        	if($(this).find('.agenda_livre').attr("data-sala") == sala){
        		$(this).find('.agenda_livre').css('background-color', 'yellow');
        	}
        });
    });
});


$('.mais_horarios').click(function(){
    $('.matriz').scrollLeft($('.matriz').scrollLeft() + 500);
});

$('.menos_horarios').click(function(){
    $('.matriz').scrollLeft($('.matriz').scrollLeft() - 500);
});

$('#prox-passo').click( function() {
    if (clicou == true){
        resetActive($(this).event, 50, 'step-3');
    } else {
        $('#modal-erro').click();
    }
});

app/views/formularios/impressao.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="text-align: center; margin-bottom: 30px; margin-top: 15px;">
    <%= image_tag("SFMSP_Logo.png", width: "225px", height: "auto", alt: "SFMSP") %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-striped table-bordered" border=0 width=100%>
      <tr>
        <td class="left">Nome do Contratante:</td>
        <td><%= @reserva.municipe %></td>
      </tr>
       <tr>
        <td class="left">Nome do Falecido:</td>
        <td><%= @reserva.falecido %></td>
      </tr>
       <tr>
        <td class="left">Número da Declaração de Óbito:</td>
        <td><%= @reserva.d_obito %></td>
      </tr>
       <tr>
        <td class="left">Cemitério:</td>
        <td><%= Cemiterio.find(@reserva.cemiterio_id).nome %></td>
      </tr>
       <tr>
        <td class="left">Velório:</td>
        <td><%= Velorio.find(@reserva.velorio_id).nome %></td>
      </tr>
       <tr>
        <td class="left">Sala:</td>
        <td><%= Velorio.find(@reserva.velorio_id).salas.index(Sala.find(@reserva.sala_id)).to_i + 1 %></td>
      </tr>
       <tr>
        <td class="left">Horario de Sepultamento:</td>
        <td><%= @reserva.sepultamento.strftime("%d/%m/%Y %H:%M") %></td>
      </tr>
       <tr>
        <td class="left">Data de Contratação:</td>
        <td><%= Time.now.in_time_zone.strftime("%d/%m/%Y %H:%M") %></td>
      </tr>
    </table>
    <a class="noPrint cibelbuttonprint" href="#" onclick="window.print();return false;">Imprimir</a>
  </div>
</div>

app/views/formularios/main.html.erb
<div class="tela-principal">
    <div class="cabecalho-principal">
        <div class="row" style="margin-right: 0px;">
        <div class="col-md-offset-3">
          <div class="step row" style="margin-top: 60px;">
              <div id="head_step-1" class="col-md-2 activestep">
                  <span class="fa fa-file-o"></span>
                  <p>Selecione o local</p>
              </div>
              <div id="head_step-2" class="col-md-2">
                  <span class="fa fa-calendar"></span>
                  <p>sala e horário</p>
              </div>
              <div id="head_step-3" class="col-md-2">
                  <span class="fa fa-leanpub"></span>
                  <p>Info. falecido</p>
              </div>
              <div id="head_step-4" class="col-md-2">
                  <span class="fa fa-book"></span>
                  <p>Conclua a reserva</p>
              </div>
          </div>
        </div>
      <div class="cancelar-reserva" style="margin-top: 10px; margin-right: 30px;"><input id="cancel_modal" class="cibelbutton" type="button" data-toggle="modal" data-target="#modal-cancel" value="Cancelar Reserva"></input></div>

    </div>
    <div class="corpo-principal">
        <%= render 'formularios/selecao_velorio' %>
        <%= render 'formularios/filtro_salas' %>
        <%= render 'formularios/dados_reserva' %>
        <%= render 'formularios/concluir_reserva' %>
    </div>
</div>


<div class="modal fade" id="modal-cancel" role="dialog">
  <div class="modal-dialog">
    <div class="cimodal tam6 col-md-offset-1">
      <div class="titulo">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Atenção!</h4>
      </div>
      <div class="conteudo-modal">
        <p>Tem certeza que deseja cancelar a reserva?</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Cancelar Reserva", root_path, class: "dangerBut", id: "cancelar_reserva" %>
        <button type="button" class="myButton" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>