config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get  'home'                 => 'home#home'
  get  'pesquisa'             => 'reservas#pesquisa'
  post 'pesquisa'             => 'reservas#pesquisa'
  get  'login'                => 'sessions#new'
  post 'login'                => 'sessions#create'
  post 'criar_funcionario'    => 'funcionarios#create'
  get 'adm'                   => 'funcionarios#adm'
  get 'index_interditar'      => 'salas#index_interditar'
  
  patch 'pre_edicao'          => 'reservas#pre_edicao'
  get  'main'                 => 'formularios#main'
  post 'filtro_salas'         => 'formularios#filtro_salas'
  post 'dados_reserva'        => 'formularios#dados_reserva'
  post 'criar_reserva'        => 'formularios#criar_reserva'
  post 'confirmar_reserva'    => 'formularios#confirmar_reserva'
  get  'impressao'            => 'formularios#impressao'
  
  post 'selecao_velorio'           => 'reservas#selecao_velorio'
  post 'velorio_interditar' => 'salas#selecao_velorio_interditar'
  patch 'interditar_sala' => 'salas#interditar_sala'

  delete 'logout'             => 'sessions#destroy'
  
  resources 'salas'
  resources 'funcionarios'
  resources 'reservas'
  resources 'justificativas'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def home
    if current_funcionario.class == Velorista
      @velorio = current_funcionario.velorio
      @reservas = @velorio.reservas.where(sepultamento: Time.now..24.hours.from_now, excluida: nil)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home_ag.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="inicio">
      <h1 class="help">O que deseja fazer?</h1>
  
      <%= link_to main_path, id: 'nova_reserva', class: "link-div" do %>
        <div class="botao_inicial">
          <i class="fa fa-file-o"></i><br>
          Nova Reserva
        </div>
      <% end %>
      
      <%= link_to pesquisa_path, class: "link-div" do %>
        <div class="botao_inicial">
            <i class="fa fa-search"></i><br>
            Pesquisar
        </div>
      <% end %>
      
      <%= link_to reservas_path, class: "link-div" do %>
        <div class="botao_inicial">
            <i class="fa fa-pie-chart"></i><br>
            Listar Reservas
        </div>
      <% end %>
  
      <% if current_funcionario.adm? %>
        <%= link_to adm_path, class: "link-div" do %>
          <div class="botao_inicial">
              <i class="fa fa-cogs"></i><br>
              Administrar
          </div>
        <% end %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/home/_home_vel.html.erb
<div class="painel col-md-10 col-md-offset-1" style="margin-top: 70px">
  <div class="titulo">
    <h2>Velório <%= @velorio.nome %></h2>
  </div>
  <div class="conteudo-painel">
    <table border="1" class="table table-striped">
      <thead>
        <tr id="home-vel">
          <th>Sala</th>
          <th>Sepultamento</th>
          <th>Atendente</th>
          <th>Falecido</th>
          <th>Munícipe</th>
          <th>Cemitério</th>
        </tr>
      </thead>
      <tbody>
        <% @reservas.order(sepultamento: :asc).each do |r| %>
        <tr>
          <td><%= Velorio.find(r.velorio_id).salas.index(Sala.find(r.sala_id)).to_i + 1 %></td>
          <td><%= r.sepultamento.strftime("%d/%m/%y %H:%M") %></td>
          <td><%= r.atendente.funcionario.nome %></td>
          <td><%= r.falecido %></td>
          <td><%= r.municipe %></td>
          <td><%= r.cemiterio.nome %></th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="painel-footer"></div>
</div>

app/views/home/home.html.erb
<% if current_funcionario.class == Atendente %>
  <%= render 'home_ag' %>
<% elsif current_funcionario.class == Velorista %>
  <%= render 'home_vel' %>
<% end %>