config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get  'home'                 => 'home#home'
  get  'pesquisa'             => 'reservas#pesquisa'
  post 'pesquisa'             => 'reservas#pesquisa'
  get  'login'                => 'sessions#new'
  post 'login'                => 'sessions#create'
  post 'criar_funcionario'    => 'funcionarios#create'
  get 'adm'                   => 'funcionarios#adm'
  get 'index_interditar'      => 'salas#index_interditar'
  
  patch 'pre_edicao'          => 'reservas#pre_edicao'
  get  'main'                 => 'formularios#main'
  post 'filtro_salas'         => 'formularios#filtro_salas'
  post 'dados_reserva'        => 'formularios#dados_reserva'
  post 'criar_reserva'        => 'formularios#criar_reserva'
  post 'confirmar_reserva'    => 'formularios#confirmar_reserva'
  get  'impressao'            => 'formularios#impressao'
  
  post 'selecao_velorio'           => 'reservas#selecao_velorio'
  post 'velorio_interditar' => 'salas#selecao_velorio_interditar'
  patch 'interditar_sala' => 'salas#interditar_sala'

  delete 'logout'             => 'sessions#destroy'
  
  resources 'salas'
  resources 'funcionarios'
  resources 'reservas'
  resources 'justificativas'
  
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  has_one :atendente
  has_one :velorista

  has_secure_password
  
  validates :nome, presence: true
  validates :rf, presence: true
  validates :password, presence: true, allow_nil: true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  def adm
  	if !current_funcionario.adm?
  		redirect_to root_url
  	end
  end
  
  def index
    @atendentes = Atendente.all
  end

  def new
  	@funcionario = Funcionario.new
  	@atendente = Atendente.new
  end

  def create
    @funcionario = Funcionario.new(func_params)
  	@atendente = Atendente.new(atendente_params)
  	if @funcionario.save
  		@atendente = Atendente.new(atendente_params)
  		@atendente.funcionario = @funcionario
  		@atendente.id = @funcionario.id
  		if @atendente.save
  			redirect_to adm_path
  		else
  			flash.now[:erro] = 'Preencha o formulário corretamente'
  			render 'new'
  		end
  	else
  		flash.now[:notice] = "Preencha o formulário corretamente"
  		render 'new'
  	end
  end
  
  def edit
    @funcionario = Funcionario.find(params[:id])
  	@atendente = Atendente.find_by(funcionario_id: params[:id])
  end
  
  def update
    @funcionario = Funcionario.find(params[:id])
  	@atendente = Atendente.find_by(funcionario_id: params[:id])
  	if @funcionario.update_attributes(func_params)
  	  @atendente = Atendente.find_by(funcionario_id: params[:id])
  		if @atendente.update_attributes(atendente_params)
  			redirect_to adm_path
  		else
  			flash.now[:erro] = 'Preencha o formulário corretamente'
  			render 'edit'
  		end
  	else
  		flash.now[:notice] = "Preencha o formulário corretamente"
  		render 'edit'
  	end
  end

  private

  def func_params
  	params.require(:funcionario).permit(:nome, :rf, :password)
  end

  def atendente_params
  	params.require(:atendente).permit(:agencia_id)
  end

end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/adm.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="inicio">
      <h1 class="help">O que deseja fazer?</h1>
      
      <%= link_to new_funcionario_path, id: 'novo_funcionario', class: "link-div" do %>      
        <div class="botao_inicial">
          <i class="fa fa-file-o"></i><br>
          Cadastrar Atendente     
        </div>
      <% end %>
      
      <%= link_to funcionarios_path, class: "link-div" do %>      
        <div class="botao_inicial">
          <i class="fa fa-pencil-square-o"></i><br>
          Editar Atendentes
        </div>
      <% end %>
  
      <%= link_to index_interditar_path, class: "link-div" do %>
        <div class="botao_inicial">
            <i class="fa fa-pie-chart"></i><br>
            Administrar Velórios
        </div>
      <% end %>
      
      <%= link_to justificativas_path, class: "link-div" do %>
        <div class="botao_inicial">
            <i class="fa fa-folder-open-o"></i><br>
            <br>  <!-- coloquei isso pq a palavra relatorio ocupa so uma linha-->
            Relatório
        </div>
      <% end %>
      
    </div>
  </div>
</div>

<div class="cancelar-reserva" style="margin-top: 10px; margin-right: 2.5%;">
  <%= link_to "Voltar", root_path, class: 'cibelbutton' %>
</div>

app/views/funcionarios/edit.html.erb
<div class="col-md-4 col-md-offset-4" style="margin-top: 55px">
  <div class="painel inicio">
    <h1 class="help">Editar atendente</h1>

    <% flash.each do |message_type, message| %>
    	<div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= form_for @funcionario do |a| %>
			<table class="table table-striped table-bordered" border=0 width=100%>
			    <tr>
			      <td class="left"><%= a.label :nome, 'Nome' %></td>
			      <td><%= a.text_field :nome %></td>
			    </tr>
			     <tr>
			      <td class="left"><%= a.label :rf, 'RF' %></td>
			      <td><%= a.text_field :rf %></td>
			    </tr>
			     <tr>
			      <td class="left"><%= a.label :senha, 'Senha' %></td>
			      <td><%= a.text_field :password %></td>
			    </tr>
			     <tr>
			     	<%= fields_for @atendente do |f| %>
			     	 <td class="left"><%= f.label :agencia_id, 'Agência' %></td>
			     	 <td><%= f.select :agencia_id, Agencia.all.collect{|x| [x.nome, x.id]} %></td>
			      <% end %>
			    </tr>
			  </table>
	    	<%= a.submit 'Confirmar edição', class: 'myButton' %>
	    	<%= link_to 'Cancelar', funcionarios_path, class: 'dangerBut' %>
			<% end %> 			   
  </div>
</div>

<div class="cancelar-reserva" style="margin-top: 10px; margin-right: 2.5%;">
  <%= link_to "Voltar", adm_path, class: 'cibelbutton' %>
</div>

app/views/funcionarios/index.html.erb
<div class="row">
  <div class="inicio">
    <h1 class="help">Escolha o atendente para editar</h1>
  </div>
</div>
<div class="row">
  <div style="text-align: center; margin-top: 10px;">
    <div class="col-md-4 col-md-offset-4">
      <div class="col-md-10 col-md-offset-1">
        <table class="data_table">
          <thead>
            <th>Nome do Atendente</th>
          </thead>
          <tbody>
          <% @atendentes.each do |a| %>
          <tr>
            <td><% f = a.funcionario %>
            <%= link_to f.nome, edit_funcionario_path(f.id), class: "btn btn-default btn-block", style: "text-overflow: ellipsis;"  %></td>
          </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
<div style="margin-bottom: 100px"></div>

<div class="cancelar-reserva" style="margin-top: 10px; margin-right: 2.5%;">
  <%= link_to "Voltar", adm_path, class: 'cibelbutton' %>
</div>

app/views/funcionarios/new.html.erb
<div class="col-md-4 col-md-offset-4" style="margin-top: 55px">
  <div class="painel inicio">
    <h1 class="help">Cadastrar novo atendente</h1>

    <% flash.each do |message_type, message| %>
    	<div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= form_for @funcionario do |a| %>
			<table class="table table-striped table-bordered" border=0 width=100%>
			    <tr>
			      <td class="left"><%= a.label :nome, 'Nome' %></td>
			      <td><%= a.text_field :nome %></td>
			    </tr>
			     <tr>
			      <td class="left"><%= a.label :rf, 'RF' %></td>
			      <td><%= a.text_field :rf %></td>
			    </tr>
			     <tr>
			      <td class="left"><%= a.label :senha, 'Senha' %></td>
			      <td><%= a.text_field :password %></td>
			    </tr>
			     <tr>
			     	<%= fields_for @atendente do |f| %>
			     	 <td class="left"><%= f.label :agencia_id, 'Agência' %></td>
			     	 <td><%= f.select :agencia_id, Agencia.all.collect{|x| [x.nome, x.id]} %></td>
			      <% end %>
			    </tr>
			    <tr>
			    	<td colspan='2'><%= a.submit 'Cadastrar', id: 'cadastrar', class: 'myButton' %></td>
			    </tr>
			  </table>
			<% end %> 			   
  </div>
</div>

<div class="cancelar-reserva" style="margin-top: 10px; margin-right: 2.5%;">
  <%= link_to "Voltar", adm_path, class: 'cibelbutton' %>
</div>