config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get  'home'                 => 'home#home'
  get  'pesquisa'             => 'reservas#pesquisa'
  post 'pesquisa'             => 'reservas#pesquisa'
  get  'login'                => 'sessions#new'
  post 'login'                => 'sessions#create'
  post 'criar_funcionario'    => 'funcionarios#create'
  get 'adm'                   => 'funcionarios#adm'
  get 'index_interditar'      => 'salas#index_interditar'
  
  patch 'pre_edicao'          => 'reservas#pre_edicao'
  get  'main'                 => 'formularios#main'
  post 'filtro_salas'         => 'formularios#filtro_salas'
  post 'dados_reserva'        => 'formularios#dados_reserva'
  post 'criar_reserva'        => 'formularios#criar_reserva'
  post 'confirmar_reserva'    => 'formularios#confirmar_reserva'
  get  'impressao'            => 'formularios#impressao'
  
  post 'selecao_velorio'           => 'reservas#selecao_velorio'
  post 'velorio_interditar' => 'salas#selecao_velorio_interditar'
  patch 'interditar_sala' => 'salas#interditar_sala'

  delete 'logout'             => 'sessions#destroy'
  
  resources 'salas'
  resources 'funcionarios'
  resources 'reservas'
  resources 'justificativas'
  
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  belongs_to :velorio
  has_many :reservas
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
	def index_interditar
	end 
	
	def selecao_velorio_interditar
		@velorio = Velorio.find(params[:velorio_id])
		respond_to do |format|
	    	format.js
	    end
	end

	def interditar_sala
		@sala = Sala.find(params[:sala][:id_edit])
		@sala.desabilitada ? desab = false : desab = true
		@sala.update_attributes(desabilitada: desab)
		desab ? a = "Interditar sala" : a = "Desinterditar sala"
    Justificativa.create(sala: @sala.id, acao: a, justificativa: params[:sala][:justificativa], atendente: current_funcionario.id, horario: Time.now.in_time_zone)
		redirect_to index_interditar_path
	end
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/salas/_velorio_interditar.html.erb
<div class="painel col-md-10 col-md-offset-1">
  <div class="titulo">
    <h2>Salas</h2>
  </div>
  <div class="conteudo-painel">
    <table border="1" class="table table-striped">
      <thead>
        <tr>
          <th>Velório</th>
          <th>Sala</th>
          <th>Existem reservas na sala?</th>
          <th>Sala interditada?</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% i = 1
           @velorio.salas.each do |s| 
        %>
        	<tr>
            <td><%= @velorio.nome %></td>
            <td><%= i %></td>
            <td><%= sala_ocupada?(s) ? "Sim" : "Não" %></td>
            <td><%= s.desabilitada ? "Sim" : "Não" %></td>
            <td>
	            <% if sala_ocupada?(s) %>
	            	Não é possível alterar essa sala
	            <% elsif !s.desabilitada %>
	            	<span type="button" id="botao_habilitar_<%= s.id %>" data-toggle="modal" data-target="#habilitar_<%= s.id %>">
                  <div class="dangerBut">
                    Interditar sala
                  </div>
                </span> 
                <% else %>
                 <span type="button" id="botao_habilitar_<%= s.id %>" data-toggle="modal" data-target="#habilitar_<%= s.id %>">
                  <div class="myButton">
                    Desinterditar sala
                  </div>
                </span> 
	            <% end %>
            </td>
          </tr>
        <% 
          i = i + 1
          end 
        %>
      </tbody>
    </table>
  </div>
  <div class="painel-footer">
  </div>
</div>

<% @velorio.salas.each do |s| %>
    <div class="modal fade" id="habilitar_<%= s.id %>" role="dialog">
    <div class="modal-dialog">
      <div class="cimodal tam6 col-md-offset-1">      
      <%= form_for s, :url => { :action => "interditar_sala" } do |f| %>
        <div class="titulo">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Atenção</h4>
        </div>          
        <div class="conteudo-modal">
          <p>Justifique a alteração</p>
          <%= f.text_area :justificativa, :required => true, :value => "" %>
          <%= f.hidden_field :id_edit, value: s.id %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Alterar", class: "dangerBut" %>
        <% end %>
          <button type="button" class="myButton" data-dismiss="modal">Manter</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/salas/index_interditar.html.erb
<div class="row" style="margin-top: 50px;">
  <div class="painel col-md-4 col-md-offset-4">
    <%= form_tag velorio_interditar_path, :method => 'post', remote: true do |f| %>
      <div class="titulo">
        <%= label_tag :velorio_id, "Selecione o local de velório" %>
      </div>
      <div class="conteudo-painel">
        <%= select_tag :velorio_id, options_for_select(Velorio.all.collect{ |v| [v.nome, v.id] }), class: 'form-control' %>
      </div>
      <div class="painel-footer">
        <%= submit_tag "Enviar", class: 'cibelbutton' %>
      </div>
    <% end %>
  </div>
  <div class="cancelar-reserva" style="margin-top: 10px; margin-right: 2.5%;">
    <%= link_to "Voltar", adm_path, class: 'cibelbutton' %>
  </div>
</div>
<div style="margin-top: 50px;">
  <div id="agenda-selecionada"></div>
  <div id="velorio-selecionado"></div>
</div>

app/views/salas/selecao_velorio_interditar.js.erb
$('#velorio-selecionado').html("<%= j render 'salas/velorio_interditar', object: @velorio %>");